### PR TITLE
remove unsupported options

### PR DESCRIPTION
**Pull request by Themandunord**
Hi @cayasso 

Can you merge and publish this ? 
It's related to the #20.

I use your package in a production app, and I have many logs related to this.

Thanks.

### CODE REVIEW

**Comment by Themandunord** [comment]
@cayasso any update ?

**Comment by pahan35** [comment]
BTW @Themandunord Travis fails due to unsupported syntax: destructuring and const are not allowed in Node.js 0.10-4.

Maybe we should rewrite them in supported way?

**Comment by pahan35** [comment]
Here is ES5 version of changes?

@cayasso should I make a PR with them?
```
        var mongoOptions = Object.assign({}, options)
        var keysToClear = ['port', 'host', 'username', 'password',
          'database', 'collection', 'compression', 'engine',
          'Promise', 'delimiter', 'prefix', 'ttl', 'count', 'hosts'];
        keysToClear.forEach(function (keyToClear) {
          delete mongoOptions[keyToClear];
        })
        _mongodb.MongoClient.connect(conn, mongoOptions, function (err, db) {
```

**Comment by Themandunord** [comment]
It seems that this repo is not maintened anymore.

So I decide to take code this driver into my project to avoid this error and to add some features.

**Comment by pahan35** [comment]
@Themandunord could you please provide to your git repo with current fix?

**Comment by pahan35** [comment]
@Themandunord I found it https://github.com/Themandunord/cacheman-mongo 

For some reason first explore show me the same repository state

**Comment by Themandunord** [comment]
I don't have any repo now. I have remove the forked repo.

And I use this lib as a local package for my company.

You just need to take this code, and this PR to fix the issue.

**Comment by Themandunord** [comment]
Oh yes, I have the repo...

**Comment by cayasso** [comment]
1.0.4 is out with the fix

**Pull request merged**
